### PR TITLE
Large File Storage and Unknown Topic Category

### PR DESCRIPTION
**Pull request by GBruening**
Added LFS, fixed some issues with the literature search.

Added unknown topic as a measure with % for each topic.

### CODE REVIEW

**Comment by alcantarar** [comment]
I probably shouldn't have committed something to this branch. I just wanted to ask if you could delete the temp files starting with *.vs, and add it to the .gitignore file if you're gonna use Visual Studio more. I think they're just environment settings that you can just keep locally.

**Comment by alcantarar** [comment]
Also, just keep 1 literature update file (most recent .md and .csv). I think one will showcase the unknown topic fine.

**Comment by alcantarar** [comment]
Unknown topic part of this PR looks good. I think we should hold off on LFS. Open new PR for just unknown topic and we can leave this LFS PR open for now.

**Review by alcantarar — CHANGES_REQUESTED** [review]
Move Unknown Topic changes to new PR, remove temp .vs files, keep just one set of .md/.csv literature update files.

**Comment by GBruening** [comment]
> Also, just keep 1 literature update file (most recent .md and .csv). I think one will showcase the unknown topic fine.

I think we should keep them for now, as it is a nice backup in case something goes wrong elsewhere.

> I think we should hold off on LFS. 

I'll split it up again, but that may mean when we go to do LFS that we have to redownload it all over and it'll break that data limit thing again.

Fixed in 1789e417a5b5f37b84dea549e87753c92c606372

**Review by alcantarar — APPROVED** [review]

**Pull request merged**
