### PR TITLE
fixes #29, fixes #31, and fixes #34 

### LINKED ISSUE #29: GUI - save CSV on topic change
GUI should update csv on topic change so that if something crashes, the csv is serves as a backup. 

@GBruening for GUI-related issues, just make sure GUI is in the name of the issue so we can keep things kinda organized. I'm adding issues to a project board where we can keep track of what's done, currently in progress, or needs to be done. 

I'll move over to a "Ryan-GUI" branch and we can just keep merging our changes to the "GUI" branch until it's ready to move to the master. Sound good?

### LINKED ISSUE #31: GUI - close window on button press
need a 'close button'

### LINKED ISSUE #34: GUI - buttons too small for large topic names
increase width of `b_dict` and `other_topics` buttons

### PR DESCRIPTION
**Pull request by alcantarar**
uses literature update from 8-8-19 (with abstracts) to test functionality

### CODE REVIEW

**Review by GBruening — COMMENTED** [review]
Where's date time used?

Also why make a def for window.destroy? Just call it in the close button call

**Comment by alcantarar** [comment]
whoops! I had datetime in there for another thing. -removing.

and good call on window.destroy, I'll just incorporate it directly.

**Comment by alcantarar** [comment]
I ran it. It has no parentheses

**Comment by alcantarar** [comment]
Clarification, it breaks *with* parentheses.

**Pull request merged**
