### PR TITLE
Updated the webscraper, updated keras model.

### PR DESCRIPTION
**Pull request by GBruening**
Web scraper now pulls from 31 pages, should be fairly easy to continue it just need to write more string parses for the new types of strings. 

Keras model is updated, getting 74% accuracy which is nice. But definitely failing at certain topics, which seem to be the topics that are combinations of other ones.

### CODE REVIEW

**Comment by GBruening** [comment]
RYAN

**Comment by alcantarar** [comment]
The difference between this branch and master is huge. I'll have to go through it offline and review it.

**Review by alcantarar — CHANGES_REQUESTED** [review]
1. What is RYANDATA_test.csv, if we're going to keep it, add it to the README.md
2.  Are the files in `/Models/` needed or are they replicates of files in `/Models/Keras_model/` and `/Models/Many_ML_models/`?

**Comment by GBruening** [comment]
I think I removed all the extaa files.

**Review by alcantarar — APPROVED** [review]

**Review by alcantarar — APPROVED** [review]

**Comment by alcantarar** [comment]
I can't get this to merge. Get a 500 server error

**Comment by alcantarar** [comment]
Files in Keras_model folder are unable to be merged with master for some reason. Currently debugging by committing/pushing files directly to master. Not ideal, but slowly "merging" this branch.

**Pull request merged**
